//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assistant.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Assistant.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Чат-лог ассистент для GTA World RU.
        ///
        ///
        ///
        ///Установленная версия: {0} {1}
        ///Директория чат-лога: {2}.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Расширенный фильтр.
        /// </summary>
        internal static string AdvancedFilter {
            get {
                return ResourceManager.GetString("AdvancedFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  потому директория &quot;{0}&quot; уже существует..
        /// </summary>
        internal static string AlreadyExistingDirectoriesWarning {
            get {
                return ResourceManager.GetString("AlreadyExistingDirectoriesWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При попытке отключить автозапуск произошла ошибка..
        /// </summary>
        internal static string AutoStartDisableError {
            get {
                return ResourceManager.GetString("AutoStartDisableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При попытке включить автозапуск произошла ошибка..
        /// </summary>
        internal static string AutoStartEnableError {
            get {
                return ResourceManager.GetString("AutoStartEnableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Эта функция перестанет работать, если вы удалите или переместите парсер в другое место..
        /// </summary>
        internal static string AutoStartWarning {
            get {
                return ResourceManager.GetString("AutoStartWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При попытке автоматического сохранения чат-лога произошла ошибка.
        ///
        ///
        ///Убедитесь, что вы выбрали несистемную директорию для пути резервного копирования..
        /// </summary>
        internal static string BackupError {
            get {
                return ResourceManager.GetString("BackupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Возникла ошибка при перемещении файлов резервной копии в новую директорию.
        /// </summary>
        internal static string BackupMoveError {
            get {
                return ResourceManager.GetString("BackupMoveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Авто бэкап: {0}.
        /// </summary>
        internal static string BackupStatus {
            get {
                return ResourceManager.GetString("BackupStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Авто бэкап был выключен, пожалуйста, если Вы хотите его использовать, то включите обратно..
        /// </summary>
        internal static string BackupTurnedOff {
            get {
                return ResourceManager.GetString("BackupTurnedOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Функция автоматического резервного копирования будет отключена, пока открыт диалог настроек, а новые настройки будут применены только после закрытия диалога настроек.
        ///
        ///
        ///Хотите продолжить?.
        /// </summary>
        internal static string BackupWillBeOff {
            get {
                return ResourceManager.GetString("BackupWillBeOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пожалуйста, выберите не корневую директорию для размещения резервной копии..
        /// </summary>
        internal static string BadBackupPath {
            get {
                return ResourceManager.GetString("BadBackupPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пожалуйста, выберите правильную диреткорию для резервного копирования или отключите автоматическое резервное копирование..
        /// </summary>
        internal static string BadBackupPathSave {
            get {
                return ResourceManager.GetString("BadBackupPathSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пожалуйста, выберите не корневой директорию вашего пути к RAGEMP..
        /// </summary>
        internal static string BadDirectoryPath {
            get {
                return ResourceManager.GetString("BadDirectoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Beta.
        /// </summary>
        internal static string Beta {
            get {
                return ResourceManager.GetString("Beta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на b.
        /// </summary>
        internal static string BetaShort {
            get {
                return ResourceManager.GetString("BetaShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} символов и {1} строк.
        /// </summary>
        internal static string CharacterCounter {
            get {
                return ResourceManager.GetString("CharacterCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текущее время: {0}.
        /// </summary>
        internal static string CurrentTime {
            get {
                return ResourceManager.GetString("CurrentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Автоматически найдена директория RAGEMP по пути {0}.
        ///
        ///
        ///Пожалуйста, найдите правильный путь вручную, если он неверен или у вас несколько установок RAGEMP..
        /// </summary>
        internal static string DirectoryFinder {
            get {
                return ResourceManager.GetString("DirectoryFinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Произошла ошибка при попытке автоматического поиска директории RAGEMP, пожалуйста, найдите ее вручную..
        /// </summary>
        internal static string DirectoryFinderError {
            get {
                return ResourceManager.GetString("DirectoryFinderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось определить путь к директории RAGEMP, найдите ее вручную..
        /// </summary>
        internal static string DirectoryFinderNotFound {
            get {
                return ResourceManager.GetString("DirectoryFinderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация (Первый запуск).
        /// </summary>
        internal static string DirectoryFinderTitle {
            get {
                return ResourceManager.GetString("DirectoryFinderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OFF.
        /// </summary>
        internal static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ON.
        /// </summary>
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://face.gtaw.me/.
        /// </summary>
        internal static string FacebrowserLink {
            get {
                return ResourceManager.GetString("FacebrowserLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://forum.gtaw.me/topic/36897-gta-world-ru-chatlog-parser.
        /// </summary>
        internal static string FeatureShowcaseLink {
            get {
                return ResourceManager.GetString("FeatureShowcaseLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При попытке удалить файл произошла ошибка..
        /// </summary>
        internal static string FileDeleteError {
            get {
                return ResourceManager.GetString("FileDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Если вы хотите отфильтровать чат-лог, в каждой строке может быть только одно слово, число или пара имен.
        ///
        ///Пример: Boat, $500, John, John Doe или John_Doe.
        /// </summary>
        internal static string FilterHint {
            get {
                return ResourceManager.GetString("FilterHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не найдено ни одного совпадения.
        ///
        ///
        ///Убедитесь, что в каждой строке есть только одно слово, число или пара правильных имен.
        ///
        ///Пример: Boat, $500, John, John Doe или John_Doe.
        /// </summary>
        internal static string FilterHintNoMatches {
            get {
                return ResourceManager.GetString("FilterHintNoMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Одно или несколько слов были пропущены в процессе фильтрации, поскольку они не имеют правильного формата.
        ///
        ///
        ///Убедитесь, что в каждой строке есть только одно слово, число или пара правильных имен.
        ///
        ///Пример: Boat, $500, John, John Doe или John_Doe.
        /// </summary>
        internal static string FilterHintSkipped {
            get {
                return ResourceManager.GetString("FilterHintSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Чат-лог{0} загружен{1}.
        /// </summary>
        internal static string FilterLogStatus {
            get {
                return ResourceManager.GetString("FilterLogStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При чтении выбранного файла произошла ошибка..
        /// </summary>
        internal static string FilterReadError {
            get {
                return ResourceManager.GetString("FilterReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://forum.gtaw.me/topic/36897-gta-world-ru-chatlog-parser.
        /// </summary>
        internal static string ForumsLink {
            get {
                return ResourceManager.GetString("ForumsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Автоматическое резервное копирование чат-лога во время игры (каждые {0} {1}).
        /// </summary>
        internal static string IntervalHint {
            get {
                return ResourceManager.GetString("IntervalHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}. (рекомендуется).
        /// </summary>
        internal static string IntervalRecommended {
            get {
                return ResourceManager.GetString("IntervalRecommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный путь к директории RAGEMP..
        /// </summary>
        internal static string InvalidDirectoryPath {
            get {
                return ResourceManager.GetString("InvalidDirectoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пожалуйста, выберите правильное расположение каталога RAGEMP, прежде чем пытаться включить автоматическое резервное копирование..
        /// </summary>
        internal static string InvalidDirectoryPathBackup {
            get {
                return ResourceManager.GetString("InvalidDirectoryPathBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пожалуйста, выберите правильное расположение каталога RAGEMP, прежде чем пытаться отфильтровать чат-лог..
        /// </summary>
        internal static string InvalidDirectoryPathFilter {
            get {
                return ResourceManager.GetString("InvalidDirectoryPathFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Язык.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбранный язык будет использоваться для извлечения журнала чата с нужного сервера.
        ///
        ///.
        /// </summary>
        internal static string LanguageInfo {
            get {
                return ResourceManager.GetString("LanguageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  в {0}.
        /// </summary>
        internal static string LoadedAt {
            get {
                return ResourceManager.GetString("LoadedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закрытие парсера приведет к тому, что автоматическое резервное копирование не будет выполняться.
        ///
        ///
        ///Не хотите ли вы вместо этого свернуть парсер в системный трей?.
        /// </summary>
        internal static string MinimizeInsteadOfClose {
            get {
                return ResourceManager.GetString("MinimizeInsteadOfClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на минут.
        /// </summary>
        internal static string MinutePlural {
            get {
                return ResourceManager.GetString("MinutePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на минута.
        /// </summary>
        internal static string MinuteSingular {
            get {
                return ResourceManager.GetString("MinuteSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хотите переместить все существующие файлы резервных копий в новую директорию?.
        /// </summary>
        internal static string MoveBackups {
            get {
                return ResourceManager.GetString("MoveBackups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обнаружено несколько каталогов ресурсов GTA World. 
        ///Рекомендуется использовать один IP для подключения к серверу и удалить другие директории ресурсов.
        ///
        ///
        ///Оставьте либо &quot;{0}&quot;, либо &quot;{1}&quot;..
        /// </summary>
        internal static string MultipleChatLogs {
            get {
                return ResourceManager.GetString("MultipleChatLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  не.
        /// </summary>
        internal static string Negation {
            get {
                return ResourceManager.GetString("Negation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не найден чат-лог GTA World.
        /// </summary>
        internal static string NoChatLog {
            get {
                return ResourceManager.GetString("NoChatLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ни один чат-лог не загружен..
        /// </summary>
        internal static string NoChatLogLoaded {
            get {
                return ResourceManager.GetString("NoChatLogLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновления не найдены.
        ///
        ///Попробуйте проверить подключение к Интернету или увеличить таймаут проверки обновлений в окне настроек.
        ///
        ///
        ///Установленная версия: {0}.
        /// </summary>
        internal static string NoInternet {
            get {
                return ResourceManager.GetString("NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы еще ничего не отфильтровали..
        /// </summary>
        internal static string NothingFiltered {
            get {
                return ResourceManager.GetString("NothingFiltered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не переместили ни одной директории в новое место..
        /// </summary>
        internal static string NothingMovedWarning {
            get {
                return ResourceManager.GetString("NothingMovedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы еще ничего не парсили..
        /// </summary>
        internal static string NothingParsed {
            get {
                return ResourceManager.GetString("NothingParsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы не ввели ни одного слова для фильтрации.
        ///
        ///
        ///Используйте стандартный фильтр, если не хотите фильтровать по словам..
        /// </summary>
        internal static string NoWordsToFilter {
            get {
                return ResourceManager.GetString("NoWordsToFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При парсинге чат-лога был обнаружен старый формат, поэтому рекомендуется удалить его и все остальные скрипты, которые не были обновлены корректно.
        ///
        ///
        ///Вы хотите удалить эти файлы?
        ///
        ///(Перед удалением файл чат-лога будет отпарсен).
        /// </summary>
        internal static string OldChatLog {
            get {
                return ResourceManager.GetString("OldChatLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы хотите открыть страницу документации по парсеру на форуме GTA World?.
        /// </summary>
        internal static string OpenDocumentation {
            get {
                return ResourceManager.GetString("OpenDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Программа уже запущена, проверьте панель задач или диспетчер задач..
        /// </summary>
        internal static string OtherInstanceRunning {
            get {
                return ResourceManager.GetString("OtherInstanceRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При парсинге чат-лога произошла ошибка..
        /// </summary>
        internal static string ParseError {
            get {
                return ResourceManager.GetString("ParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Переместите в новое место только директории &quot;{0}&quot;..
        /// </summary>
        internal static string PartialMoveWarning {
            get {
                return ResourceManager.GetString("PartialMoveWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://github.com/0Z0SK0/GTAWRU-Log-Parser.
        /// </summary>
        internal static string ProjectLink {
            get {
                return ResourceManager.GetString("ProjectLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Question.
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://github.com/0Z0SK0/GTAWRU-Log-Parser/releases.
        /// </summary>
        internal static string ReleasesLink {
            get {
                return ResourceManager.GetString("ReleasesLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перезапуск.
        /// </summary>
        internal static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы используете последнюю версию парсера.
        ///
        ///
        ///Установленная версия: {0}.
        /// </summary>
        internal static string RunningLatest {
            get {
                return ResourceManager.GetString("RunningLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Один и тот же чат-лог был сохранен {0} или более раз, это означает, что скрипт клиента RAGEMP, отвечающий за регистрацию вашего чата, сломан.
        ///
        ///
        ///Это происходит при потере интернет-соединения или падении сервера. 
        ///Единственным известным способом устранения проблемы является удаление каталогов ресурсов сервера, на котором вы играете.
        ///
        ///
        ///Потерянный чат-лог не может быть восстановлен..
        /// </summary>
        internal static string SameHashWarning {
            get {
                return ResourceManager.GetString("SameHashWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При попытке сохранить файл произошла ошибка..
        /// </summary>
        internal static string SaveError {
            get {
                return ResourceManager.GetString("SaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на секунд.
        /// </summary>
        internal static string SecondPlural {
            get {
                return ResourceManager.GetString("SecondPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на секунда.
        /// </summary>
        internal static string SecondSingular {
            get {
                return ResourceManager.GetString("SecondSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки будут применены только после того, как вы закроете диалог настроек..
        /// </summary>
        internal static string SettingsAfterClose {
            get {
                return ResourceManager.GetString("SettingsAfterClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стандартный фильтр.
        /// </summary>
        internal static string SimpleFilter {
            get {
                return ResourceManager.GetString("SimpleFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начать.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Успешно отпарсен и сохранен чат-лог в {0}.
        /// </summary>
        internal static string SuccessfulBackup {
            get {
                return ResourceManager.GetString("SuccessfulBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Чтобы переключиться на выбранный сервер, парсеру необходимо перезапуститься.
        ///
        ///
        ///Хотите ли вы применить изменения и перезапустить приложение сейчас?.
        /// </summary>
        internal static string SwitchServer {
            get {
                return ResourceManager.GetString("SwitchServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://ucp.gtaw.me/.
        /// </summary>
        internal static string UCPLink {
            get {
                return ResourceManager.GetString("UCPLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}..
        /// </summary>
        internal static string UpdateAbortTime {
            get {
                return ResourceManager.GetString("UpdateAbortTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новая версия парсера доступна на GitHub.
        ///
        ///
        ///Установленная версия: {0}
        ///
        ///Доступная версия: {1}
        ///
        ///
        ///
        ///Хотите перейти на страницу релиза прямо сейчас?.
        /// </summary>
        internal static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновление доступно.
        /// </summary>
        internal static string UpdateAvailableTitle {
            get {
                return ResourceManager.GetString("UpdateAvailableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}{1}.
        /// </summary>
        internal static string VersionInfo {
            get {
                return ResourceManager.GetString("VersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Предупреждение.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
